<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <script>
      // Promiseチェーン

      // Promise .then(ok_callback, ng_callback)
      // Promise .then((ok_value) => {}, (ng_value) => {})

      // Promise .catch(ng_callback) NGはcatch
      // Promise .catch((ng_reason) => {})

      function promiseTest4(pay) {  //ok
        return new Promise(ok => {
          let change = pay - 100;
          ok(change);
        });
      }

      // ngも追加
      // new Promise((ok, ng) => {});

      function promiseTest4(pay) {   //NG
        return new Promise((ok, ng) => {
          if(pay >= 100) {
            let change = pay - 100;
            ok(change);
          }
            ng('お金が足りません');
        });
      }

      console.log(promiseTest4(80).catch(e => {console.log(e)}));

      promiseTest4(180).then(change1 => {
        console.log(change1);
        return promiseTest4(change1); //Promiseでラップ ok(value)
      }).then(change2 => {
        console.log(change2);
      }).catch(e => console.log(e));

      // どこでエラーが出ているかわかるようにPromiseの最後にはcatchをつける
    </script>
  </body>
</html>
